### ISSUE TITLE
DOC/README: please officially make this a general working extension

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#143]
Now, that it also works with Theia. both offline and online (just tested) it would be a good opportunity to adjust the README and the repo summary.

@spgennard are you accepting a PR to do this? It would effectively drop/replace "Visual Studio Code" in some places (while keeping it or replace it to "vscode" or "[vscode](https://github.com/Microsoft/vscode)-based editors" in other places).

_Originally posted by @GitMensch in https://github.com/spgennard/vscode_cobol/issues/123#issuecomment-622936878_

**Comment by spgennard** [comment]
I would need to try out Theia, as I concerned that some of the features in the extension may not work too well, as it uses "node" to access the file system rather than using apis provided by vscode.   

The bottom line, is that I would need to feel comfortable with it before documenting I support it.

**Comment by GitMensch** [comment]
Sounds perfectly fine (I'd still vote for an "experimental support" note and for replacing "Visual Studio Code" (the product build on top of vscode + the "Visual Studio Code Marketplace", proprietary extensions and telemetry packaged as proprietary executables you are not able to share) by vscode (which actually provides nearly all the goodies we use).
