### ISSUE TITLE
"record-data" variable in all red

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#149]
I guess it is somewhat special, but I don't have a clue why...
![sample](https://user-images.githubusercontent.com/6699539/84325451-0e738400-ab7b-11ea-8527-83df868ccf76.png)

**Comment by spgennard** [comment]
record-data is valid in AcuCOBOL-GT for everyone else it's isn't, so it is highlighted so you can ensure your code is portable.

https://www.microfocus.com/documentation/extend-acucobol/925/BKINRHINUI5U.html

**Comment by GitMensch** [comment]
It isn't in its reserved word list:
https://www.microfocus.com/documentation/extend-acucobol/925/GUID-45E064B5-D77F-4DA4-8E5F-A6D957BDEDCF.html

But this does highlight an important issue: Wouldn't it be reasonable to be able to add/remove reserved words for the highlighter? Is there an option to do so without recompiling the extension?

**Comment by spgennard** [comment]
The item has the scope "invalid.illegal.acu.cobol", so you can tweak the highlighting in settings.

No, it's not possible to add/remove the reserved word list on fly but as I said above you can it in settings eg:

```json
"editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "invalid.illegal.acu.cobol",
                "settings": {
                    "foreground": "#ffffff"
                }
            }
        ]
    }
```

or make it specific to your chosen theme.

The closest you can get is to apply semantic highlighting but this will still require all the reserved words to be present and unless you are analyzing the code for dialect then it will be painful for the user, as it is not easy to determine what dialect the code is written for, because it might be compliant with one dialect but be required to execute on another which behaves differently at runtime.

**Comment by spgennard** [comment]
Okay, no follow up for a while, so I'll assume it's all good.

**Comment by GitMensch** [comment]
Rechecked:

ACUCOBOL dialect has it as reserved word in blue -> reasonable
COBOL (which I consider to be the "portable" one) in red -> explained by you above, fine
Enterprise for z/OS dialect has it as user defined word in white -> fine
MF not found (I guess we're going with "COBOL" here)
OpenCOBOL/GnuCOBOL is red again -> I'd say reserved words that it should be the same as in Enterprise for z/OS; either there "red" or (my preference here) "white" in both.

... and to this special word: it is not on the ACUCOBOL reserved word list itself and a "type attribute" used in a ACUCOBOL-GT only "heavy extension" of the screen section.
