### ISSUE TITLE
Extension does not work with remote files loaded via SSH FS

### ISSUE THREAD

**Issue by cobolcowboy** [spgennard/vscode_cobol#158]
**Describe the bug**
When editing files loaded via a remote filesystem via the [SSH FS extension](https://marketplace.visualstudio.com/items?itemName=Kelvin.vscode-sshfs) most (all?) extension features are disabled. I don't get the outline, I can't jump to any definitions, I can't peek, these options aren't even present in the context menu. I'm using SSH FS to connect to some older machines that don't support Microsoft's remote SSH extension. 

**To Reproduce**
1. Install [SSH FS extension](https://marketplace.visualstudio.com/items?itemName=Kelvin.vscode-sshfs)
2. Load a remote file
3. Try to use any extension features

**Expected behavior**
I would expect to still have these features available.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version 6.3.19

**Additional context**
I mentioned this in another issue and figured I'd actually file this report since this has been an issue I've run into daily for a long time, it would be great if I could still use this extension with remote files.

**Comment by cobolcowboy** [comment]
Actually after thinking about this I decided to try a work around and was able to get things working with [SSH-FS for Windows](https://github.com/billziss-gh/sshfs-win). The extension seems to work fine when I use this to handle the connection instead of the SSH FS VS Code extension. So I guess I'll close this since it seems to just be an issue with that extension.

**Comment by spgennard** [comment]
The SSH FS extension introduces a new virtual filesystem under the schema called 'ssh'.

Features in this extension are registered under the 'file' extension because it depends on the file system in order to function.

For example it uses various function in 'fs', 'path'.   These are used for caching, file searching and more.


I recommend you move from this extension to Microsoft's own remote SSH, which works much better:
   https://code.visualstudio.com/docs/remote/ssh

**Comment by cobolcowboy** [comment]
Thanks, however that extension is not compatible with my target environment (HPUX). Like I said I was able to use SSH-FS for Windows to handle the connection outside the editor and your extension works great with that.
