### ISSUE TITLE
coboleditor.copybookdirs is auto-unset

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#168]
**Describe the bug**
Setting of coboleditor.copybookdirs in the current workspace or folder does not work.

**To Reproduce**
0. create a folder "test" with some files and folders (= just copy anything; no COBOL sources in the root), create a new folder "copy" with a copybook in there,
open the editor, open test folder, install current cobol.bitlang
1. Go to extension setting of this plugin (UI, workspace)
2. Click on 'add element' for the copybookdirs setting
3. enter 'copy' and press "ok"
4. See error:
    * the setting ui switchtes to "user"
    * the copybookdirs setting has a note "changed in workspace"
    * there's a new dropdown "folders" which now contains "test" and "copy"
    * .vscode/settings.json has `"coboleditor.copybookdirs": []`

**Expected behavior**
New folder added to the setting (which works fine when adding a copybook extension).

**Additional context**
Happens on different OS all with newest vscodium (so it is hard to say if this is a vscode error or an extension one).

**Comment by spgennard** [comment]
Change "coboleditor.migrate_copybooks_directories_to_workspace" to false

The direction of travel is remove "coboleditor.copybookdirs"

**Comment by GitMensch** [comment]
Both changing the default migration setting to false and adding copybooks + the restoring the default and adding the entries manually to the `folders` worked. As you've said that coboleditor.copybookdirs will be removed I've used the later.

**Comment by kabel** [comment]
@spgennard:

I'm a bit confused by the new settings and what specifically they're trying to migrate. I still very much appreciate having the `coboleditor.copybookdirs` as it provides an elegant way to support fallback paths for copybooks that I want to override locally. 

Example Workspace:

- `CopyBooks\Shared`
  - `foo.cbl`
  - `bar.cbl`
- `Shared`
  - `foo.cbl`
- `main.cbl`

When `main.cbl` has `COPY "Shared\bar.cbl"` vs `COPY "Shared\foo.cbl"` I get what I expect with the settings:

```json
    "coboleditor.copybookdirs": [
        "CopyBooks"
    ],
    "coboleditor.migrate_network_copybooks_directories_to_workspace": false
```

With `coboleditor.migrate_network_copybooks_directories_to_workspace = true` my references to `Shared\bar.cbl` because `CopyBooks` is (in workspace) being ignored. I know ambiguous paths are weird, but it's a helpful feature when I have an _expected_ order of which path will get used. My assumption has always been that the `coboleditor.copybookdirs` are evaluated/scanned __in the order defined__ and the first file that is found wins (is parsed) and all other candidate paths are ignored (short-circuited). With this scheme, I also assumed the default `${workspaceFolder}` would be searched first. That's how it mostly worked a few versions ago.

**Comment by spgennard** [comment]
When ```coboleditor.migrate_network_copybooks_directories_to_workspace = true``` is set any network copybook directories are removed and added to the current workspace.

None of these folders are network folders, so are not migrated.   

So no behaviour difference will be observed.

If you have files that have the same name in more than one place, then as the order of the workspace evaluation is not defined, the result will also be undefined too.   

The COBOL language goes a step further and states two programs of the same name cannot be present in the same run unit.

**Comment by GitMensch** [comment]
I agree that it is important to have a guaranteed order here. Especially if you have multiple projects with common copybooks that may be in a different version in one single project, it is reasonable to have it "locally" and override the shared one.
The last time I've tested this (January?) this worked as expected, so what can we do to do the same in the future?

**Comment by kabel** [comment]
OK. I think my underlying dilemma stems from the change at https://github.com/spgennard/vscode_cobol/commit/71cfba8532cf5d8 that essentially removed the ability to reference copybooks at the root of the workspace if you have `coboleditor.copybookdirs` defined with a workspace root relative item (at least through the paragraph definition provider).

Attached is an example workspace that I'm dealing with and the user config set. [TempWorkspace.zip](https://github.com/spgennard/vscode_cobol/files/4955501/TempWorkspace.zip) 
It contains a similar scenario that @GitMensch is describing. There is a different version of `foo.cbl` in one of the include directories.

Here are the screenshots and debug output while testing with versions 6.2.16 and 6.5.20:

__6.2.16__ - Missing paragraph definition for super.

```
Extension Information:
 Extension path    : ~\.vscode\extensions\bitlang.cobol-6.2.16
 Version           : 6.2.16
 Caching           : on
  Cache directory  : ~\Temp\.vscode_cobol
  Search directory : ~\Desktop\Temp
  Search directory : ~\Desktop\Temp\CopyBooks
  Search directory : ~\Desktop\Temp\OldCopyBooks
```

![image](https://user-images.githubusercontent.com/675956/88093275-65478280-cb57-11ea-8b04-9d595d80415e.png)
![image](https://user-images.githubusercontent.com/675956/88093284-68427300-cb57-11ea-8671-67e08eb6a47b.png)
![image](https://user-images.githubusercontent.com/675956/88093292-6bd5fa00-cb57-11ea-97f9-8907e4bd0330.png)
![image](https://user-images.githubusercontent.com/675956/88093304-71334480-cb57-11ea-9e7c-63346f88535e.png)

__6.5.20__ - Issues:

* can go-to-definition for `Shared\super.cbl`, but not `PERFORM super` 
* `~\Desktop\Temp` is not considered in the search directories
* the definition of `PERFORM foo` comes from `CopyBooks\Shared\foo.cbl` rather than the preferred (first in the `copybookdirs` array) `.\Shared\foo.cbl`

```
Extension Information:
 Extension path    : ~\.vscode\extensions\bitlang.cobol-6.5.20
 Version           : 6.5.20
 Caching                       : on
  Cache Strategy               : storagepath
  Cache directory              : ~\AppData\Roaming\Code\User\workspaceStorage\3eebe35166fcdfa304baa94cc27552b5\bitlang.cobol
  UNC paths disabled           : false
 Parse copybook for references : true
  Workspace Folders
   => ~\Desktop\Temp
  CopyBook Search directories (2)
   => ~\Desktop\Temp\CopyBooks
   => ~\Desktop\Temp\OldCopyBooks
  CopyBook Search directories (logical)
   => ${workspaceFolder}/CopyBooks ${workspaceFolder}/OldCopyBooks 
```

(super hovers are the same as 6.2.16)

![image](https://user-images.githubusercontent.com/675956/88093363-860fd800-cb57-11ea-81d1-570f74d951f1.png)
![image](https://user-images.githubusercontent.com/675956/88093369-8ad48c00-cb57-11ea-9196-56da22e03692.png)

Most compilers have some way of resolving ambiguous copy/include file references. Like giving the compiler an ordered list (`-I` of gnucobol) of directories to search/qualify the file. I'm not sure how microfocus handles it, but their manual does reference that it's possible. Enterprise compilers have library list, etc. I'm treating the `coboleditor.copybookdirs` config value as this ordered list. Is there some issue with treating it that way and establishing that as expected behavior?

I know the a program still has to maintain distinct references to compile, but that should not bother a loose parser.

**Comment by spgennard** [comment]
Have you tried setting parse_copybooks_for_references?

**Comment by kabel** [comment]
Yes, just tried it work the example workspace with no noticeable difference.

**Comment by spgennard** [comment]
Just debugging it and found it is because "super" is a keyword.

**Comment by kabel** [comment]
I figured that was the case. That's a minor issue compared to getting the _old_ `foo` definition rather the definition from the directory I preferred it come form.

**Comment by spgennard** [comment]
note: the "\" "/" in a copy statement is invalid in some dialects

**Comment by kabel** [comment]
I understand. Thankfully the dialect I use (and the extension parses) does.

**Comment by spgennard** [comment]
I can't find a way of moving the directories around in the project either.

https://github.com/microsoft/vscode/issues/44205

**Comment by kabel** [comment]
I don't think relying on vscode to build the workspace folders an expose them through in API in a _preferred_ order is appropriate. The preference of parsing order should remain in the extension. You might consider merging `coboleditor.copybookdirs` and the workspace roots with some kind of algorithm or configuration.

**Comment by spgennard** [comment]
I tend to agree but I need to think about it more.

**Comment by GitMensch** [comment]
Should we track this under a new issue or should I rename the issue and we reopen it?`(I'm fine with both).
