### ISSUE TITLE
Paragraphs in Copy file used for code not showing as referenced

### ISSUE THREAD

**Issue by RollMasterJW** [spgennard/vscode_cobol#185]
**Describe the bug**
When a paragraph is declared in a copy file and used in another file it doesn't show as having been referenced when open.

**To Reproduce**
Attached is a project that exhibits the behavior. The program file (MAIN.CBL) has the CODE.CPY file as a copybook and when opening the copybook file it doesn't show the paragraphs as having been referenced anywhere.

**Expected behavior**
Paragraphs would show as being referenced and allow for 'Find all references' to see where the paragraph had been peformed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/68345529/89795381-f1612000-daed-11ea-8f4f-bb6232b9703f.png)
![image](https://user-images.githubusercontent.com/68345529/89795413-fb831e80-daed-11ea-8823-049cbf4ebbf8.png)

**What user & workspace settings are being used?:**
 - AcuCobol GT 9

[Temp.zip](https://github.com/spgennard/vscode_cobol/files/5051564/Temp.zip)

**Comment by spgennard** [comment]
Hi,

Unfortunately, Visual Studio Code does not understand copybook's (or has any concept of nested files), so as each file is opened is treated as if it is a separate file and has no relationship with the file it was opened from.   This makes it impossible for COPY.cpy to know that any references are to be found in MAIN.cbl.   

Editors in full-sized IDEs such as Visual COBOL for Visual Studio 2019 have specific support for this type of scenario and handle it well, as they implement copybook views/editors.

I can understand these messages can appear to be overwhelming with a large copybook, if this is the case you have two options:

1 - Disable the linting for FOO, BAR via a comment:

```cobol
      *> cobol-lint ignore FOO BAR
```

or

2 - Change the severity of the messages from informational to hint, this means the paragraph name's colour is reduced.

The information will only appears when you hover over the paragraph and the problem is not included in the problems panel.

```json
    "coboleditor.linter_mark_as_information": false
````

**Comment by RollMasterJW** [comment]
I've been trying to make heads or tails of the code for the ReferenceProvider class in the code without much luck. I would have assumed it would look through all files and not really cared if there was a direct reference from the copy book to any other particular file, though that could get messy in projects that have programs that call other paragraphs with similar or same names under different files. I guess there is a problem if you go either way, with returning all or returning only from the local file. 

Is there a way we can allow it to see into every file for references though a flag in the settings?

**Comment by spgennard** [comment]
The reference providers work off the current document and I then supplement it by parsing any copybook in context.

What you can do is search through all files. eg:  Edit, Find in Files (or Ctrl+Shift+F - default key binding, Cmd+Shift+F on MacOS) to search the Currently open Folder.

**Comment by GitMensch** [comment]
> Unfortunately, Visual Studio Code does not understand copybook's (or has any concept of nested files), so as each file is opened is treated as if it is a separate file and has no relationship with the file it was opened from. This makes it impossible for COPY.cpy to know that any references are to be found in MAIN.cbl.

So similar messages and the reference counter in other extensions come from a language-server that does the linting, while in this case it comes from the extension itself and this can't work because vscode doesn't provide the missing bits, correct?

**Comment by spgennard** [comment]
The issue is that vscode is a file editor and each file is treated individually, so has not parent or context.

The concept of a context is important, as the copybook will most likely be used from many places, each context could have a different "use" of the copybook.

IDEs get arround this by having custom COBOL editors & handle the copybook themselves, including having read-only view on expanded copybook (copy replacing).

**Comment by GitMensch** [comment]
> The issue is that vscode is a file editor and each file is treated individually, so has not parent or context.

I see.

But the extension _could_ have an internal view on the file and include the context there, couldn't it?
If not: Can you please create an issue at https://github.com/microsoft/vscode/ about adding support for whatever is missing in vscode?

**Comment by spgennard** [comment]
You could have a virtual view but it would not allow you to edit (because it is a view).

The only option is to replace the editor and provide a COBOL sensitive editor but that is a massive job and given how slow the javascript is at parsing large files and how bad vscode is at handling large files (it turns off colourisation) I don't think this is a viable thing todo.

**Comment by GitMensch** [comment]
Hm, so the C and Java editors use an own editor but bitlang.cobol has no own editor and use a "plain one + syntax highlighting"?
Or is a possible speed improvement the result of using a language server?

I'd really like to understand the issue...

**Comment by spgennard** [comment]
No, C and Java use the same mechanism... ie: use standard text editor with colourisation & language customization.

Java source has no context, each file is dedicated to a class etc.. and has no macro or include mechanism.
C/C++ has headers and you get the same class of issue... ie: you treat a header file as a non-header.

COBOL is unique in that has no convention for extensions and a copybook could also be a complete file too... only the compiler will know this for sure.

What I am looking to do is turn off all linting for anything that is believed to be a copybook, which is perhaps the only sensible thing to do.

I did move my code to a language server and because it is out of process and COBOL files are very large, the parsing took much longer because it has to send the file over http/grpc and do the same amount of parsing and send the results back... so actually for me.. it makes things worse.

**Comment by GitMensch** [comment]
Thanks for the explanation.

**Comment by RollMasterJW** [comment]
What about putting a comment header in the beginning of the copy files to denote 'this is used by X.cbl file' and/or 'this is a copybook' so that it knows where/how to look for additional references? It would be minimal overhead for the end user but could expand the functionality of the extension quite well.

**Comment by GitMensch** [comment]
That wouldn't work - often the copybooks are used in multiple files and with COPY REPLACING they may not look identical from the program's view.

**Comment by GitMensch** [comment]
... and with active and up-to-date metadata the extension should already know which copybook is used in which program (@spgennard if this isn't the case then it is likely good to add this piece of information)

**Comment by spgennard** [comment]
The problem is the copybook can be used in many different places, so
you would need something like this and then ask the user which he is
using.

For example, in one of my application is has a "footer" copybook for
standard sections (plus matching working-storage copybook) and only
some of the sections are used.. very rarely will they all be used.

Then if this copybook is consumed by another copybook then the
references have to be backtracked through it too... etc..

Not an easy one to solve.


On Wed, 12 Aug 2020 at 14:38, RollMasterJW <notifications@github.com> wrote:
>
> What about putting a comment header in the beginning of the copy files to denote 'this is used by X.cbl file' and/or 'this is a copybook' so that it knows where/how to look for additional references? It would be minimal overhead for the end user but could expand the functionality of the extension quite well.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
--
Stephen Gennard
stephen@gennard.net
