### ISSUE TITLE
external cobscanner increasing the download size nearly 15 times

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#227]
I've just recognized that with the external cobscanner, which was first shipped with https://github.com/spgennard/vscode_cobol/releases/tag/6.8.6 the download size (39.5MB) increased very much, compared to https://github.com/spgennard/vscode_cobol/releases/tag/6.8.5 with 2.65MB.
The size difference roots in extension\bin where we have a binary for win32, macos, linux (11-14 MB packed, 35-40MB unpacked).

Questions:

* Is there any documentation on the external scanner already?
* What is the external scanner used for?
* Is it something that is comparable to a language-server?
* If it is - should it be a separate binary (to limit size and work on more environments, for example ARM is now officially supported even in Visual Studio Code and I guess the currentl linux binary won't work on it)?

**Comment by spgennard** [comment]
You have raised an issue on something that has not been published... is this the right place to raise the issue.. perhaps a question about it would be a more friendly and better use of my time.

> Is there any documentation on the external scanner already?

They will be no documentation as it is an implementation detail on how the metadata is scanned... who cares if this is an in-process function or an out-of-process feature or a combination of both?

> What is the external scanner used for?
Scanning source code!

>  Is it something that is comparable to a language-server?
No, otherwise it would be called a language server

> If it is - should it be a separate binary (to limit size and work on more environments, for example ARM is now officially supported even in Visual Studio Code and I guess the currentl linux binary won't work on it)?

I have no intention to separate the binaries from the extension, as they are interdependent on each other and I don't want to host anything myself let alone want to incur the cost of hosting them.

The download size should not be an issue, for example, if we are using a pre-historic  28k Modem dialup, it will take 3mins which is acceptable but using a modern 4G mobile connection it might download in 4 seconds.. which is even more acceptable.

The size of the extension is still smaller than other COBOL/language extensions, so I am also not concerned about the size.

When the extension is published, I expect the non-platform related binaries will be cleaned up or soon afterward.

Lastly, If the platform does not have an external binary, it will drop back to the in-process version providing the same functionality but in a less vscode friendly way but will still function.

**Comment by GitMensch** [comment]
Thank you for all those good information. I want to ensure you that I don't create any issue to criticize, but to ask and possibly bring in suggestions.

It was an "issue" for me as (for whatever reason) the download took more than 2 minutes which was quite different to the earlier version and an additional one when seeing the actual binaries which can never target "every system on the world" [it seems most language servers therefore use Java, but spawing many java processes is performance-wise likely not a good idea].
As long as there's a working fallback (which seems to be even feature-identical) everything is fine for me.
Side question out of interest: Is there already a note about the use of a fallback in the extension output?

We do have a label "question" here, would you like questions to be asked different than creating an issue in this repo?

> They will be no documentation as it is an implementation detail on how the metadata is scanned... who cares if this is an in-process function or an out-of-process feature or a combination of both?

Hm, people that may want to contribute to this repo via code?

**Comment by GitMensch** [comment]
Just for reference, https://github.com/spgennard/vscode_cobol/releases/tag/6.9.11 moved it back to the old size using node fork instead of spawning a native executable, for details see https://github.com/spgennard/vscode_cobol/issues/215#issuecomment-716068167.
