### ISSUE TITLE
Issue with metadata in storagepath

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#243]
_Originally posted in https://github.com/spgennard/vscode_cobol/issues/242_

@spgennard said
> I am seriously thinking about removing the storagepath support as I received complaints about it.
> The complaint I get is the "creeping" size of the storage area and "removing my source code" does not remove the cache (not unexpected)

@GitMensch replied
> Please don't [remove the storage path option], that's the only way for our programmers to work with the extension at all - they can't write to the workspace path, only to single files that are checked-out before [... and] in any case it is an optional non-default setting.
> I [think] that's something a complete metadata parsing either handles already or could do relative easily.

@spgennard pointed out
> No because the area is "orphaned" from the workspace config.. ie: nothing references it

So here is the issue to handle that.

**Comment by spgennard** [comment]
There is no solution for this, so I am unsure what you honestly expect to be done.  

The only viable solutions are:
- do not use storage path
- remove it

You are pushing me to do the later... do you really want this?

**Comment by GitMensch** [comment]
>The only viable solutions are:
> * do not use storage path

I agree that it would be bad to do so per default. I've thought the default is `off`, it it isn't then this seems most reasonable.
If people explicit set this they should be aware of the pro and con (documentation could help).

> remove it

As it is something people explicit choose and #161 requested it for similar reasons that I have I think this should not be done.
There may could be an option "remove all metadata from storagepath for all workspaces" which would get the current folder (so one before "bitlang.cobol" and then go up one directory and then iterate all sub-directories - deleting all "bitlang.cobol" folders found there --> all workspaces clean.

But I think the "pollution" issue is a general vscode issue and would be best handled there (but others like the one about handling both "warning" and "Warnung" are too and are closed on the vscode side).

**Comment by GitMensch** [comment]
> You are literally the only person with this problem.

The idea for the storagepath in #161 was from @kabel, so I _guess_ I'm not the only one (actually: my companies place [and strangely also my the one in the company I've worked before]).

As I've said: having a default of `"coboleditor.cache_metadata": "off"´ or `"coboleditor.cache_metadata": "workspace"` and a note about "old stuff won't be deleted automatically because that's the way vscode works" for the `storagepath` option should be fine in my point of view.

**Comment by kabel** [comment]
Forgive me if I'm not following the thread(s) properly. I don't understand what this issue is. Files are starting to pile up in your storagepath (Windows: appdata) folder that don't seem to be managed by the extension? Doesn't seem like a big deal, but maybe the cache files for your workspaces add up quickly. I look at these files just like I do any other temporary,  transient file not generated specifically by a user (think browser cache and cookies).

Just like it's the user's personal preference to _not_ store these files in the same folder as the user created files--I would flip out if my browser started dropping cache files on my desktop--if you think the storage folder is getting too big, manually delete it. If that breaks the extension, that's probably poor error handling, but probably easy to recover from.

----

Some general observations about the tone of the thread:

>You are literally the only person with this problem.

You'd be well advised to avoid hyperbole like this. Many end-user issues go unreported. {insert picture of me rage-clicking something on my work Windows machine}

> The use of the storage area is flawed and this is the reality of the situation

That seems like a bold claim. If you think it's flawed, please help by linking to some references or a vscode issue.

> My chain of thought is:
> * remove the storage area support
> * for "storage area" users, they can use a symbolic link to a different area on disk or turn off caching
> * lastly, if this is not acceptable the brutal recommendation is to move to a different IDE or COBOL plugin

That escalated quickly. We went from general user nuisance to removing a helpful feature in 3-2-1. Was this in jest? Claims like that lead to forks, community division.

Also symlinks are much easier to manage by a machine that can trivially reorganize things so they stay out of my way. If the answer is for me to manually manage symlinks in _literally_ thousands of different workspaces, I asked the wrong question. Too error prone for everyone to get right.
