### ISSUE TITLE
Question: partial move of GnuCOBOL relate parts - will other languages follow?

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#244]
For reasons I do not understand so far most of the GnuCOBOL related parts were moved to https://github.com/spgennard/vscode_cobol4gnucobol (the configuration is still doubled here btw). I _guess_ this was about the license, but as both are MIT-licensed again it may be possible to couple them again, too?

Will the other languages all get a separate extension, that depends on this too?

Does this mean that I'll have to install:

* GnuCOBOL
* OpenCOBOL
* MF
* MF-SE
* COBOL-IT
* ProCOBOL
* auto-installed because of the dependency: bitlang.cobol

and others may install

* JCL
* HLASM
* ACUCOBOL
* ...

I primarily want to understand the reason to have it separated now and know what is planned to be additional separated.

Thanks for sharing your thoughts.

**Comment by spgennard** [comment]
The intention is to separate the GnuCOBOL from the core support and remove the dependency on this extension allowing it to used with other extensions.

**Comment by spgennard** [comment]
The GnuCOBOL extensions can now be used with other COBOL language extensions or continue to be used with this... It has been liberated and let loose into the world.

**Comment by GitMensch** [comment]
Thank you. I see now how it can work, given the remove of "depends.on" and agree that this is good. The only thing that got lost which I see so far are the tests - I don't know enough of this but the testrunner may could be moved out to a node.js-module and then used in other extensions for testing the pattern matchers, too.
Wouldn't it be reasonable to also include GnuCOBOL's "family" in there (OpenCOBOL [removed here] and COBOL-IT [the bad cousin])?

And then maybe also separate MF from the main extension allowing it to be used with other extensions, too?

**Comment by spgennard** [comment]
I have been told numerous times that OpenCOBOL is dead and superceded by numerous versions of GnuCOBOL.

I world prefer to keep the GnuCOBOL extension for non commercial/open source offerings.

If someone "new" raises an issue about OpenCOBOL, then I will look into It.

The work on the GnuCOBOL is not complete and I am aware If the missing tests.

P.s. not sure about COBOL-IT being the bad cousin, it is a complete solution based on its OpenCOBOL cousin.  Including eclipse support etc...  It has a purpose for some people.

**Comment by spgennard** [comment]
The tests have now been transferred.

https://github.com/spgennard/vscode_cobol4gnucobol/tree/main/src/test

**Comment by GitMensch** [comment]
> The tests have now been transferred.

Thank you for the transferred tests.

> I world prefer to keep the GnuCOBOL extension for non commercial/open source offerings.
> If someone "new" raises an issue about OpenCOBOL, then I will look into It.

I see. the reason to keep it in is mainly: it is identical to the one used for opensource-COBOL, which is definitely still active (and has a port that generates Java instead of C). I agree that the split at "free" (there are numerous commercial applications with OpenCOBOL/GnuCOBOL/opensource-COBOL) is a very reasonable one.

COBOL-IT definitely has a purpose (even when most people tell me that the purpose was heavily countered by the move of its owner), and it definitely should stay available in this extension.

The only open question is: do you agree that it could be useful to also move out other dialects? The way the current split is done is quite clean and it would allow people to have a "pure" extension, without JCL/HLASM, maybe even without MF and mfdir.

**Comment by spgennard** [comment]
As, I've said if the OpenCOBOL people are welcome to come back and request it and I will consider what do then (in a positive way) but I think the GnuCOBOL support will be enough for them.

I think the OpenCOBOL4J project has a long.. long way to get to a place where it requires the use of an editor... at this point, I suspect they will lean towards using a traditional java enabled editor rather than.

Just look at how little is happening...   https://github.com/opensourcecobol/opensourcecobol4j/commits/develop


I can't really answer that because the concept of a "pure" extension seems odd to me because the products/compilers it can be used with includes jcl, hlasm, bms (or can be used with a third-party provider), so why would I want to separate them?

I am not sure what you mean by MF (if you mean Micro Focus), this is basically the core dialect, so why would I remove it?

**Comment by GitMensch** [comment]
With "pure" I meant COBOL only, with the option to integrate the others as needed. People that primarily want a fast viewer/editor without actual compiling would use that, people don't have MF (MicroFocus) or ACU (ACUCOBOL) licensed will just add the GnuCOBOL (GC) extension, other people only MF and some will take nearly all.

>  the products/compilers it can be used with includes jcl, hlasm, bms, so why would I want to separate them?

Because people that are COBOL-on-PC-people (which are quite much) use none of those (or are even aware of them).
Those are _only_ relevant for software that initially came from the Mainframe, and are either still using it or use a MicroFocus (or Fujitsu, or Heirloom, third party) emulator/compiler and then do want to have it. For the PC people it doesn't matter at all, so moving these out (possibly combined into one "mainframe target", likely together with the ibm dialect) seems useful to me.

**Comment by spgennard** [comment]
The speed of viewing COBOL is not affected by the inclusion of other language colourizers.

I will respectfully won't be creating a "pure" extension because at least one extension exists already that fulfills this need and I know you are aware of it. 

https://github.com/shashi278/cobol-lang-syntax
https://github.com/shashi278/cobol-lang-syntax/issues/3

So, let the visual studio ecosystem tend to everyone's needs.. no reason to create duplicates

> Because people that are COBOL-on-PC-people (which are quite much) use none of those (or are even aware of them).
Those are only relevant for software that initially came from the Mainframe, and are either still using it or use a MicroFocus (or Fujitsu, or Heirloom, third party) emulator/compiler and then do want to have it. For the PC people it doesn't matter at all, so moving these out (possibly combined into one "mainframe target", likely together with the ibm dialect) seems useful to me.

I don't agree, a lot of people work in mixed/hybrid environments or offload environments, so the need to view/edit a mixture of COBOL related assets is helpful.

Fujitsu, Heirloom are not supported dialects of COBOL supported by this extension.   These platforms have specific needs and are catered for by their specific vendors.

**Comment by GitMensch** [comment]
> So, let the visual studio ecosystem tend to everyone's needs.. no reason to create duplicates

Agreed.

> a lot of people work in mixed/hybrid environments or offload environments, so the need to view/edit a mixture of COBOL related assets is helpful.

I totally agree to that, too, and see how my message can seen as possibly questioning that.
My point was NOT to remove it in any part but to make it optional, by moving it out to another extension, either integrated as bitlang.gnucobol with pure optional but also self-standing, or as an extension of this extension that works with dependson (if I understand this correctly using the "mixed-language" version would then automatically install the COBOL one, with its base dialect microfocus - but all the people that don't work in a mixed/hybrid environment don't have it.

> Can I sincerely ask you to wrap up these questions because it feels like we are going in circles and it isn't the first time you have quizzed me on such items.

I haven't seen this first as it was an edit... Hm, yes, I at least try (the only reason that this one came up again was the split).
If I did not make that clear before: I definitely appreciate the work you do with this extension very much.
