### ISSUE TITLE
please provide a way to skip the external extension check

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#302]
This check is very reasonable and useful in general, _especially_ in the initial setup for users.

What I'd like to see is either an option "don't remind me any more" on the popup or a setting to manually specify this.
In both cases there could be a boolean setting "skip_extension_check" or a list "user_blessed_extensions".

I'd again PR this if you want to, just would to need which way to go.

**Comment by spgennard** [comment]
I am happy with the current solution and it has helped diagnose a fair few issues.

The key purpose is to inform the user that an integration issue should be raised with the external extension author to ensure it becomes compliant.   

Once this is done, it should ensure the external author contacts me about mitigation/issue resolution strategies, therefore ensuring the issue is fixed for all, not just one person.

Lastly, I don't wish to introduce a popup, as the check is during extension initialisation and ignoring an active popup may cause the extension to be not fully initialised.

**Comment by GitMensch** [comment]
Thanks for this information, guess I will trigger this process for some extensions. Can you please point me to a list of compliance points I can check/forward?
