### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by GiaTasso** [spgennard/vscode_cobol#304]
- Issue Type: `Performance`
- Extension Name: `cobol`
- Extension Version: `7.10.30`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.61.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\G4DB7~1.TAS\AppData\Local\Temp\bitlang.cobol-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by spgennard** [comment]
You also need to include any settings as well.

**Comment by alespiga** [comment]
I have same problem. When starting vscode, this message appears

![image](https://user-images.githubusercontent.com/48070375/141677507-df15305e-94fa-4d95-b645-209bd6bf3e15.png)
![image](https://user-images.githubusercontent.com/48070375/141677487-26e57efa-792d-440c-b9f1-a084b49d8118.png)
i attach the file [bitlang.cobol-unresponsive.cpuprofile.txt](https://github.com/spgennard/vscode_cobol/files/7533565/bitlang.cobol-unresponsive.cpuprofile.txt)

My settings:

- Extension Name: `cobol`
- Extension Version: `v7.11.1`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `v1.62.2`
- workspace settings : [workspace-settings.zip](https://github.com/spgennard/vscode_cobol/files/7533571/workspace-settings.zip)

I have a git repository which unfortunately needs some resources to compile on a remote server. The server is mapped on windows as a network path.
Recently, my copybooks were not displaying correctly with [CTRL+click] so I added the property `"coboleditor.parse_copybooks_for_references": true`
Could this have caused the problem?

**Comment by spgennard** [comment]
Yes, using copybook parsing is the reason:

![image](https://user-images.githubusercontent.com/5991192/141680725-9955aac6-795b-485f-bd2f-5378807f5541.png)

This is due to the long search path specified in the coboleditor.copybookdirs property.

This may be made worse If your drive K: is a network drive or if it is a slow rusty disk drive.

**Comment by GitMensch** [comment]
I've previously seen a similar issue (also: network drive), which was totally solved back than with changing to:
* caching metadata
* resolve metadata once at startup

This way it took only one time long to do the lookups, then - because only some sources get a new timestamp - it only takes a bit more time during startup, but it generally works and has no big penalty on the startup time of the workspace.
I _guess_ the related settings were `coboleditor.process_metadata_cache_on_start`, `coboleditor.maintain_metadata_cache`, `coboleditor.cache_metadata_show_progress_messages`.

**Comment by alespiga** [comment]
I'll change my workspace and i'll give feedback next days.

Thanks a lot!

**Comment by spgennard** [comment]
@GiaTasso Please note `coboleditor.cache_metadata_show_progress_messages` is scheduled for removal but luckily for you, it will have no impact on the caching you are looking to enable

**Comment by GiaTasso** [comment]
@spgennard and @GitMensch Thank you, I made the changes recommended to @alespiga in my workspace and everything seems to work better, I will also give future feedback
