### ISSUE TITLE
FR: Cobol Parser

### ISSUE THREAD

**Issue by jakobwgnr** [spgennard/vscode_cobol#70]
Hello!
First of all - nice work on this extension!

I've read through the issues and have seen that you are looking for/working on an cobol parser.

I've started working a parser (mainly on the purpose of learning typescript). 
[https://github.com/jakobwgnr/zion-lexer](https://github.com/jakobwgnr/zion-lexer)
[https://github.com/jakobwgnr/zion-parser](https://github.com/jakobwgnr/zion-parser)

Both repos are in alfa-state (the parser not yet finished even & have to be refactored), but maybe you can use it somehow or at least reference on this. 

Best Regards!

**Comment by spgennard** [comment]
Thanks, it's good to know and it might be something I would use in other projects.

I have already wrote a simple loose parser/lexer that givens me just enough to get a reasonable outliner.

I've avoided creating a more complete parser as COBOL because unfortunately as it does not have one standard or a dominant variant to basis it on.

To be a viable COBOL parser it would it have to understand the following dialects:

- AcuCOBOL
- Micro Focus COBOL (12+ levels)
 + Procedural
 + Object Oriented COBOL
 + Managed COBOL
- Microsoft COBOL 
- Fujitsu COBOL
- NEC COBOL
- IBM Enterprise COBOL
 + VS Cobol
 + COBOL/370
 + MVS/VM COBOL
 + OS/390 COBOL
 + Enterprise COBOL
 + COBOL LE
 + AIX COBOL
- ICL COBOL
- MBP COBOL
- LegacyJ COBOL
- Heirloom COBOL
- RM/COBOL
- OpenCOBOL, GnuCOBOL
- COBOL-IT
- Dell COBOL
- HP COBOL
... and I bet more..

So, at this point I thought.. this is too big to get right, so I took a more pragmatic approach to the parsing.

**Comment by jakobwgnr** [comment]
Hehe - Thanks for your feedback. did not think about the varying dialects yet...

**Comment by spgennard** [comment]
If you start looking at the different dialects, let us know I might be able to help.

**Comment by jakobwgnr** [comment]
cool ! Do you have some good source, that shows the different dialects, so that I could check on that?

**Comment by spgennard** [comment]
This is a really good guide:

Visual COBOL -A DEVELOPER’S GUIDE TO MODERN COBOL
 https://www.microfocus.com/media/ebook/visual_cobol_ebook.pdf

The LRM for this product:
 Visual COBOL/Enterprise COBOL - 
  https://www.microfocus.com/documentation/visual-cobol/vc40pu2/DevHub/GUID-D84DDFBC-3D1E-47B1-8DEF-26B322C321F6.html

Then, some mainframe related COBOL's:

IBM Enterprise COBOL for z/OS - LRM v4r2 -  https://www.ibm.com/support/knowledgecenter/SS6SG3_4.2.0/com.ibm.entcobol.doc_4.2/PGandLR/igy3lr50.pdf

UniSys
 https://public.support.unisys.com/aseries/docs/clearpath-mcp-17.0/pdf/86001518-316.pdf

and more..

Fujitsu COBOL2000 - http://manuals.ts.fujitsu.com/file/2772/cob2_bs.pdf

RM/COBOL - LRM - https://www.microfocus.com/documentation/rm-cobol/1214/RMC-LRM.pdf

I will look at add these and other references to a wiki entry/readme.
